<?php
/* START - AI settings */

function mini_ai_settings_init() {
    register_setting( 'mini_ai', 'mini_ai_settings', [
        'sanitize_callback' => 'mini_ai_sanitize_settings',
    ] );
    add_settings_section(
        'mini_ai_section',
        __( 'AI settings', 'mini' ),
        '__return_false',
        'mini-ai'
    );
}
add_action( 'admin_init', 'mini_ai_settings_init' );

function mini_ai_sanitize_settings( $input ) {
    $input = is_array( $input ) ? $input : [];

    $input['mini_ai_enabled']       = ! empty( $input['mini_ai_enabled'] ) ? 1 : 0;
    $input['mini_ai_global_policy'] = in_array( $input['mini_ai_global_policy'] ?? '', [ 'allow', 'disallow', 'custom' ], true )
        ? $input['mini_ai_global_policy']
        : 'allow';

    if ( isset( $input['mini_ai_custom_rules'] ) ) {
        $input['mini_ai_custom_rules'] = sanitize_textarea_field( $input['mini_ai_custom_rules'] );
    }

    $known_bots  = mini_ai_get_known_bots();
    $bot_policies = [];
    foreach ( $known_bots as $bot_key => $bot_info ) {
        $policy = $input['mini_ai_bot_policies'][ $bot_key ] ?? 'inherit';
        $bot_policies[ $bot_key ] = in_array( $policy, [ 'inherit', 'allow', 'disallow' ], true ) ? $policy : 'inherit';
    }
    $input['mini_ai_bot_policies'] = $bot_policies;

    return $input;
}

function mini_ai_get_known_bots() {
    return [
        'gptbot'             => [ 'name' => 'GPTBot',             'company' => 'OpenAI',        'purpose' => __( 'Web crawling for ChatGPT / GPT model training', 'mini' ) ],
        'chatgpt-user'       => [ 'name' => 'ChatGPT-User',       'company' => 'OpenAI',        'purpose' => __( 'ChatGPT browsing plugin requests', 'mini' ) ],
        'oai-searchbot'      => [ 'name' => 'OAI-SearchBot',      'company' => 'OpenAI',        'purpose' => __( 'OpenAI search index crawler', 'mini' ) ],
        'anthropic-ai'       => [ 'name' => 'anthropic-ai',       'company' => 'Anthropic',     'purpose' => __( 'Crawling for Claude AI training', 'mini' ) ],
        'claudebot'          => [ 'name' => 'ClaudeBot',          'company' => 'Anthropic',     'purpose' => __( 'Claude AI web browsing', 'mini' ) ],
        'google-extended'    => [ 'name' => 'Google-Extended',    'company' => 'Google',        'purpose' => __( 'Google Bard / Gemini AI training (opt-out)', 'mini' ) ],
        'perplexitybot'      => [ 'name' => 'PerplexityBot',      'company' => 'Perplexity',    'purpose' => __( 'Perplexity AI search crawling', 'mini' ) ],
        'ccbot'              => [ 'name' => 'CCBot',              'company' => 'Common Crawl',  'purpose' => __( 'Common Crawl dataset (used by many AI models)', 'mini' ) ],
        'cohere-ai'          => [ 'name' => 'cohere-ai',          'company' => 'Cohere',        'purpose' => __( 'Cohere AI model training', 'mini' ) ],
        'bytespider'         => [ 'name' => 'Bytespider',         'company' => 'ByteDance',     'purpose' => __( 'TikTok / ByteDance AI training', 'mini' ) ],
        'meta-externalagent' => [ 'name' => 'Meta-ExternalAgent', 'company' => 'Meta',          'purpose' => __( 'Meta AI (Llama) training', 'mini' ) ],
        'amazonbot'          => [ 'name' => 'Amazonbot',          'company' => 'Amazon',        'purpose' => __( 'Amazon Alexa AI training', 'mini' ) ],
    ];
}

function mini_ai_get_txt_content() {
    $opts          = get_option( 'mini_ai_settings', [] );
    $global_policy = $opts['mini_ai_global_policy'] ?? 'allow';
    $bot_policies  = $opts['mini_ai_bot_policies']  ?? [];
    $known_bots    = mini_ai_get_known_bots();

    if ( $global_policy === 'custom' ) {
        $custom = trim( $opts['mini_ai_custom_rules'] ?? '' );
        if ( $custom !== '' ) {
            return $custom . "\n";
        }
        // Empty custom field — fall through to default generated content.
    }

    $lines = [];
    $lines[] = '# ai.txt — AI crawler policy';
    $lines[] = '# Generated by mini plugin — ' . home_url( '/ai.txt' );
    $lines[] = '';
    $lines[] = 'User-agent: *';
    $lines[] = ( $global_policy === 'allow' ) ? 'Allow: /' : 'Disallow: /';

    // Per-bot overrides
    foreach ( $known_bots as $bot_key => $bot_info ) {
        $policy = $bot_policies[ $bot_key ] ?? 'inherit';
        if ( $policy === 'inherit' ) {
            continue;
        }
        $lines[] = '';
        $lines[] = '# ' . $bot_info['company'];
        $lines[] = 'User-agent: ' . $bot_info['name'];
        $lines[] = ( $policy === 'allow' ) ? 'Allow: /' : 'Disallow: /';
    }

    $lines[] = '';

    return implode( "\n", $lines );
}

function mini_ai_page_html() {
    if ( ! current_user_can( 'manage_options' ) ) {
        return;
    }

    if ( isset( $_GET['settings-updated'] ) ) {
        add_settings_error( 'mini_messages', 'mini_message', __( 'Settings Saved', 'mini' ), 'updated' );
    }
    settings_errors( 'mini_messages' );

    $current_tab = isset( $_GET['tab'] ) ? sanitize_key( $_GET['tab'] ) : 'general';
    $page_url    = admin_url( 'admin.php?page=mini-ai' );

    $opts          = get_option( 'mini_ai_settings', [] );
    $enabled       = ! empty( $opts['mini_ai_enabled'] );
    $global_policy = $opts['mini_ai_global_policy'] ?? 'allow';
    $bot_policies  = $opts['mini_ai_bot_policies']  ?? [];
    $custom_rules  = $opts['mini_ai_custom_rules']  ?? '';
    $known_bots    = mini_ai_get_known_bots();
    $preview       = mini_ai_get_txt_content();
    ?>
    <div class="wrap">
        <h1><?php echo esc_html( get_admin_page_title() ); ?></h1>

        <nav class="nav-tab-wrapper">
            <a href="<?php echo esc_url( $page_url . '&tab=general' ); ?>" class="nav-tab <?php echo $current_tab === 'general' ? 'nav-tab-active' : ''; ?>"><?php _e( 'AI Policy', 'mini' ); ?></a>
            <a href="<?php echo esc_url( $page_url . '&tab=bots' ); ?>" class="nav-tab <?php echo $current_tab === 'bots' ? 'nav-tab-active' : ''; ?>"><?php _e( 'Bot rules', 'mini' ); ?></a>
            <a href="<?php echo esc_url( $page_url . '&tab=preview' ); ?>" class="nav-tab <?php echo $current_tab === 'preview' ? 'nav-tab-active' : ''; ?>"><?php _e( 'Preview', 'mini' ); ?></a>
        </nav>

        <form action="options.php" method="post">
            <?php
            settings_fields( 'mini_ai' );
            do_settings_sections( 'mini-ai' );
            ?>

            <?php if ( $current_tab === 'general' ) : ?>

                <div class="boxes align-items-start">

                    <div class="box-100 p-2 grad-3-to-4 b-rad-5 box-shadow">
                        <h4 class="white-text"><?php esc_html_e( 'Enable ai.txt', 'mini' ); ?></h4>
                        <label for="mini_ai_enabled" class="white-text">
                            <input type="checkbox" id="mini_ai_enabled" name="mini_ai_settings[mini_ai_enabled]" value="1" <?php checked( $enabled ); ?> class="me-1">
                            <?php esc_html_e( 'Serve an ai.txt file to declare your AI crawling policy.', 'mini' ); ?>
                        </label>
                        <p class="S false-white-text">
                            <?php esc_html_e( 'ai.txt is an emerging standard — analogous to robots.txt — that tells AI companies how they may crawl and use your content. Responsible AI providers honour it.', 'mini' ); ?>
                            <?php if ( $enabled ) : ?>
                            &nbsp;<a href="<?php echo esc_url( home_url( '/ai.txt' ) ); ?>" target="_blank" rel="noopener" class="false-white-text"><?php esc_html_e( 'View your ai.txt', 'mini' ); ?> &rarr;</a>
                            <?php endif; ?>
                        </p>
                    </div>

                    <div class="box-50 p-2 white-bg b-rad-5 box-shadow">
                        <h4><?php esc_html_e( 'Global AI policy', 'mini' ); ?></h4>
                        <p class="S grey-text"><?php esc_html_e( 'Default rule applied to all AI crawlers not covered by a specific bot rule.', 'mini' ); ?></p>
                        <select name="mini_ai_settings[mini_ai_global_policy]" id="mini_ai_global_policy">
                            <option value="allow"    <?php selected( $global_policy, 'allow' ); ?>><?php esc_html_e( 'Allow — AI crawlers can access all content', 'mini' ); ?></option>
                            <option value="disallow" <?php selected( $global_policy, 'disallow' ); ?>><?php esc_html_e( 'Disallow — Block all AI crawlers', 'mini' ); ?></option>
                            <option value="custom"   <?php selected( $global_policy, 'custom' ); ?>><?php esc_html_e( 'Custom — write your own rules', 'mini' ); ?></option>
                        </select>
                        <p class="S grey-text mt-1"><?php esc_html_e( 'Use the "Bot rules" tab to override the policy for individual AI crawlers.', 'mini' ); ?></p>
                    </div>

                    <div class="box-50 p-2 white-bg b-rad-5 box-shadow" id="mini_ai_custom_rules_box" style="<?php echo $global_policy !== 'custom' ? 'display:none;' : ''; ?>">
                        <h4><?php esc_html_e( 'Custom rules', 'mini' ); ?></h4>
                        <p class="S grey-text"><?php esc_html_e( 'Write your own ai.txt content. Uses the same syntax as robots.txt.', 'mini' ); ?></p>
                        <textarea name="mini_ai_settings[mini_ai_custom_rules]" rows="12" style="width:100%;font-family:monospace;"><?php echo esc_textarea( $custom_rules ); ?></textarea>
                        <p class="S grey-text"><?php esc_html_e( 'When "Custom" is selected, Bot rules are ignored and this content is served as-is.', 'mini' ); ?></p>
                    </div>

                </div>

            <?php elseif ( $current_tab === 'bots' ) : ?>

                <div class="boxes align-items-start">
                    <div class="box-100 p-2 white-bg b-rad-5 box-shadow">
                        <h4><?php esc_html_e( 'Per-bot rules', 'mini' ); ?></h4>
                        <p class="grey-text"><?php esc_html_e( '"Default" inherits the global policy. Override individual crawlers here.', 'mini' ); ?></p>
                        <?php if ( $global_policy === 'custom' ) : ?>
                        <p class="S" style="color:#d63638;"><?php esc_html_e( 'Note: per-bot rules are ignored when "Custom" is selected as the global policy.', 'mini' ); ?></p>
                        <?php endif; ?>
                        <div class="boxes">
                        <?php foreach ( $known_bots as $bot_key => $bot_info ) :
                            $policy = $bot_policies[ $bot_key ] ?? 'inherit';
                        ?>
                        <div class="box-50 p-2 white-bg b-rad-5 border">
                            <h5 class="mb-0">
                                <?php echo esc_html( $bot_info['name'] ); ?>
                                <span class="flag XS px-05 b-rad-5 grey-text border grey-border"><?php echo esc_html( $bot_info['company'] ); ?></span>
                            </h5>
                            <p class="S grey-text mt-05 mb-1"><?php echo esc_html( $bot_info['purpose'] ); ?></p>
                            <select name="mini_ai_settings[mini_ai_bot_policies][<?php echo esc_attr( $bot_key ); ?>]">
                                <option value="inherit"  <?php selected( $policy, 'inherit' ); ?>><?php esc_html_e( 'Default (inherit global policy)', 'mini' ); ?></option>
                                <option value="allow"    <?php selected( $policy, 'allow' ); ?>><?php esc_html_e( 'Allow', 'mini' ); ?></option>
                                <option value="disallow" <?php selected( $policy, 'disallow' ); ?>><?php esc_html_e( 'Disallow', 'mini' ); ?></option>
                            </select>
                        </div>
                        <?php endforeach; ?>
                        </div>
                    </div>
                </div>

            <?php elseif ( $current_tab === 'preview' ) : ?>

                <div class="boxes align-items-start">
                    <div class="box-100 p-2 white-bg b-rad-5 box-shadow">
                        <h4><?php esc_html_e( 'ai.txt Preview', 'mini' ); ?></h4>
                        <p class="S grey-text"><?php esc_html_e( 'This is the content that will be served at', 'mini' ); ?> <code><?php echo esc_html( home_url( '/ai.txt' ) ); ?></code>.</p>
                        <?php if ( $enabled ) : ?>
                        <p>
                            <a href="<?php echo esc_url( home_url( '/ai.txt' ) ); ?>" target="_blank" rel="noopener" class="btn fourth-color-btn white-text S">
                                <?php esc_html_e( 'View live ai.txt', 'mini' ); ?> &rarr;
                            </a>
                        </p>
                        <?php else : ?>
                        <p class="S" style="color:#d63638;"><?php esc_html_e( 'Enable ai.txt (General tab) to serve this file.', 'mini' ); ?></p>
                        <?php endif; ?>
                        <textarea readonly rows="20" style="width:100%;font-family:monospace;background:#f6f7f9;"><?php echo esc_textarea( $preview ); ?></textarea>
                    </div>
                </div>

            <?php endif; ?>

            <?php submit_button( 'Save Settings' ); ?>
        </form>
    </div>
    <script>
    (function () {
        var sel = document.getElementById('mini_ai_global_policy');
        var box = document.getElementById('mini_ai_custom_rules_box');
        if (sel && box) {
            sel.addEventListener('change', function () {
                box.style.display = this.value === 'custom' ? '' : 'none';
            });
        }
    }());
    </script>
    <?php
}

/* END - AI settings */


/* START - ai.txt endpoint */

function mini_ai_rewrite_version() {
    return '1';
}

function mini_ai_register_rewrite_rules() {
    add_rewrite_rule( '^ai\.txt$', 'index.php?mini_ai_txt=1', 'top' );
}
add_action( 'init', 'mini_ai_register_rewrite_rules' );

function mini_ai_query_vars( $vars ) {
    $vars[] = 'mini_ai_txt';
    return $vars;
}
add_filter( 'query_vars', 'mini_ai_query_vars' );

function mini_ai_serve_txt() {
    if ( ! get_query_var( 'mini_ai_txt' ) ) {
        return;
    }

    $opts = get_option( 'mini_ai_settings', [] );

    if ( empty( $opts['mini_ai_enabled'] ) ) {
        status_header( 404 );
        exit;
    }

    $content = mini_ai_get_txt_content();

    header( 'Content-Type: text/plain; charset=UTF-8' );
    header( 'Cache-Control: public, max-age=3600' );
    echo $content;
    exit;
}
add_action( 'template_redirect', 'mini_ai_serve_txt' );

function mini_ai_maybe_flush_rewrite_rules() {
    if ( ! is_admin() || ! current_user_can( 'manage_options' ) ) {
        return;
    }

    $current = get_option( 'mini_ai_rules_version' );
    $target  = mini_ai_rewrite_version();

    if ( $current === $target ) {
        return;
    }

    mini_ai_register_rewrite_rules();
    flush_rewrite_rules( false );
    update_option( 'mini_ai_rules_version', $target, false );
}
add_action( 'admin_init', 'mini_ai_maybe_flush_rewrite_rules' );

function mini_ai_activation_setup() {
    mini_ai_register_rewrite_rules();
    flush_rewrite_rules();
    update_option( 'mini_ai_rules_version', mini_ai_rewrite_version(), false );
}

function mini_ai_deactivation_teardown() {
    flush_rewrite_rules();
}

/* END - ai.txt endpoint */
